trigger:
- main

pool:
  name: 'COMP367-DevOps Agent'  # Self-hosted Windows agent

variables:
  buildConfiguration: 'Release'
  outputDir: '$(Build.ArtifactStagingDirectory)\nuget'  # Backslashes for Windows

steps:
# Install .NET 8 SDK
- task: UseDotNet@2
  inputs:
    version: '8.x'

# Create output directory explicitly
- script: mkdir "$(outputDir)"
  displayName: 'Create NuGet output directory'

# Build TestPackage
- script: dotnet build TestPackage/TestPackage.csproj --configuration $(buildConfiguration)
  displayName: 'Build TestPackage'

# Pack TestPackage
- script: dotnet pack TestPackage/TestPackage.csproj --configuration $(buildConfiguration) --output "$(outputDir)"
  displayName: 'Pack TestPackage'

# Verify the .nupkg file exists
- script: dir "$(outputDir)"
  displayName: 'Check NuGet package exists'

# Authenticate with Azure Artifacts
- task: NuGetAuthenticate@1
  displayName: 'Authenticate with Azure Artifacts'

# Push TestPackage.1.0.0.nupkg
- task: PowerShell@2
  displayName: 'Push TestPackage to Azure Artifacts'
  inputs:
    targetType: inline
    script: |
      $packagePath = "$(outputDir)\TestPackage.1.0.0.nupkg"
      if (Test-Path $packagePath) {
          dotnet nuget push $packagePath `
            --source "https://pkgs.dev.azure.com/nneedha1/1b5aa350-91f7-4285-bd87-d5f20c9989f0/_packaging/MyTeamFeed/nuget/v3/index.json" `
            --api-key AzureDevOps
      } else {
          Write-Error "TestPackage.1.0.0.nupkg not found!"
      }