trigger:
- main

pool:
  name: 'COMP367-DevOps Agent'

variables:
  buildConfiguration: 'Release'
  outputDir: '$(Build.ArtifactStagingDirectory)\nuget' 

steps:
- task: UseDotNet@2
  inputs:
    version: '8.x'

# Explicitly create directory first
- script: mkdir "$(outputDir)"
  displayName: 'Create output directory'

# Build the SPECIFIC LIBRARY PROJECT (not solution)
- script: dotnet build StringLibrary\StringLibrary.csproj --configuration $(buildConfiguration)
  displayName: 'Build Library Project'

# Pack the SPECIFIC LIBRARY PROJECT
- script: dotnet pack StringLibrary\StringLibrary.csproj --configuration $(buildConfiguration) --output "$(outputDir)"
  displayName: 'Pack StringLibrary'

# Diagnostic step
- script: dir "$(outputDir)"
  displayName: 'List files in output directory'

- task: NuGetAuthenticate@1
  displayName: 'Authenticate with Azure Artifacts'

# Push only StringLibrary (explicit filter)
- task: PowerShell@2
  displayName: 'Push StringLibrary'
  inputs:
    targetType: inline
    script: |
      $packagePath = Join-Path -Path "$(outputDir)" -ChildPath "StringLibrary.1.0.0.nupkg"
      if (Test-Path $packagePath) {
          dotnet nuget push $packagePath `
            --source "https://pkgs.dev.azure.com/nneedha1/1b5aa350-91f7-4285-bd87-d5f20c9989f0/_packaging/MyTeamFeed/nuget/v3/index.json" `
            --api-key BWMKyl9j2z6RTebLjGGyVn9cevwp6wBPif7DwoGApNutC3jJwXj0JQQJ99BDACAAAAAnPw96AAASAZDOARHJ
      } else {
          Write-Error "StringLibrary.1.0.0.nupkg not found!"
      }