trigger:
- main

pool:
  name: 'COMP367-DevOps Agent'

variables:
  buildConfiguration: 'Release'
  outputDir: '$(Build.ArtifactStagingDirectory)/nuget'

steps:
- task: UseDotNet@2
  inputs:
    version: '8.x'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build project'

- script: dotnet pack --configuration $(buildConfiguration) --output $(outputDir)
  displayName: 'Pack NuGet package'

# Diagnostic step: list files in the output directory
- script: dir "$(outputDir)"
  displayName: 'List files in output directory'

- task: NuGetAuthenticate@1
  displayName: 'Authenticate with Azure Artifacts'

# Push the library package
- task: PowerShell@2
  displayName: 'Push TestPackage'
  inputs:
    targetType: inline
    script: |
      $nupkgFiles = Get-ChildItem -Path "$(outputDir)\*.nupkg"
      foreach ($file in $nupkgFiles) {
        dotnet nuget push $file.FullName `
          --source "https://pkgs.dev.azure.com/nneedha1/.../nuget/v3/index.json" `
          --api-key AzureDevOps
      }